### PR TITLE
Basic support for Scala 3 and update libraries to latest versions

### LINKED ISSUE #18: Scala.js 1.0 Support
Would it be possible to add support for Scala.js 1.0?

### PR DESCRIPTION
**Pull request by lolgab**
Fixes #18 
Closes #16

### CODE REVIEW

**Comment by lolgab** [comment]
@tindzk Are you interested in merging this PR and releasing a new version for Scala 3 support?

**Comment by lolgab** [comment]
CI is now green https://github.com/lolgab/toml-scala/actions/runs/11415850054

**Comment by tindzk** [comment]
Thank you for your pull request, @lolgab. Unfortunately, I am no longer maintaining this library. If you are interested in taking over maintenance, I would be happy to link to your fork in the README and then archive this repository.

**Comment by keynmol** [comment]
Hi @tindzk!

@lolgab and I talked and I've set up a fork over at https://github.com/indoorvivants/toml-scala – it's already publishing releases (https://index.scala-lang.org/indoorvivants/toml-scala) and I've added a badge acknowledging the original repository.

With that, this PR can be closed, and if you could please link the fork in the README/description that would be great. 

Thanks for all your work!

**Comment by tindzk** [comment]
Thanks for taking over the maintenance of this project! I have updated the README and will be archiving the repository shortly.

**Pull request closed without merging**
